export const categories = [
  {
    key: '-NSrJ_yRU38knd4rZG03',
    slug: 'ngon-tinh',
    title: 'Ngôn Tình',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJ_yTMAVBhTAO0aVK',
    slug: 'phat-giao',
    title: 'Phật Giáo',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJ_yUbBp02BC1_ZaX',
    slug: 'ky-nang-song',
    title: 'Kỹ Năng Sống',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJ_zrHWo7nSL6bUFs',
    slug: 'hoc-duong',
    title: 'Học Đường',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJ_zvq0KpwapQj2in',
    slug: 'song-yeu-thuong',
    title: 'Sống Yêu Thương',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJ_zxUj0Nii0SY3BH',
    slug: 'tinh-yeu',
    title: 'Tình Yêu',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJ_zyjaJ5YHHFbcwl',
    slug: 'khoi-nghiep',
    title: 'Khởi Nghiệp',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJa--DMVwrtkL4aCQ',
    slug: 'tuoi-moi-lon',
    title: 'Tuổi Mới Lớn',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJa0VDaidKf-bKP8W',
    slug: 'kinh-dien-the-gioi',
    title: 'Kinh Điển Thế Giới',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJa0eSVu4LWkkbZJ4',
    slug: 'truyen-xua',
    title: 'Truyện Xưa',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJa0hXAIXEpZ0NWEH',
    slug: 'suc-khoe',
    title: 'Sức Khỏe',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJa20-DMOW9eYC90g',
    slug: 'ma---kinh-di',
    title: 'Ma - Kinh Dị',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJa21OGHmEtPIDKrT',
    slug: 'phieu-luu-tham-hiem',
    title: 'Phiêu Lưu-Thám Hiểm',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJaB031Eo__q_B-x9',
    slug: 'van-hoc-viet-nam',
    title: 'Văn Học Việt Nam',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJaB3PJVuO-QZobPl',
    slug: 'thien-dinh',
    title: 'Thiền Định',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJaLMM5dAcu-KbPh_',
    slug: 'marketing-ban-hang',
    title: 'Marketing-Bán Hàng',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJaM63QzUlGWSXDi9',
    slug: 'day-lam-giau',
    title: 'Dạy Làm Giàu',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJaMy0c4tFUHhCdct',
    slug: 'quan-tri-doanh-nghiep',
    title: 'Quản Trị Doanh Nghiệp',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJaQS-WrfCZ-zEVwa',
    slug: 'phat-trien-ban-than',
    title: 'Phát Triển Bản Thân',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJabwHMqgSzY1PeZF',
    slug: 'lich-su-trung-hoa',
    title: 'Lịch Sử Trung Hoa',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJaiexoPcD2JpNBwY',
    slug: 'lich-su-viet-nam',
    title: 'Lịch Sử Việt Nam',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJalk5T9xtVmx_5GP',
    slug: 'trinh-tham',
    title: 'Trinh Thám',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJalr19nMQngwFFdY',
    slug: 'khoa-hoc-tam-linh',
    title: 'Khoa Học Tâm Linh',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJaluCmLVdT49gXpL',
    slug: 'truyen-gia-tuong',
    title: 'Truyện Giả Tưởng',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJam3zk51aVqbq0R4',
    slug: 'thieu-nhi',
    title: 'Thiếu Nhi',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJamWdPwAd6o02Bcf',
    slug: 'kinh-ke',
    title: 'Kinh Kệ',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJaq77ViGjPTMovTQ',
    slug: 'ky-nang-lam-viec',
    title: 'Kỹ Năng Làm Việc',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJaq9XrxqpXmDkgUa',
    slug: 'phu-nu',
    title: 'Phụ Nữ',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJaqOW9j_jADtQcu7',
    slug: 'hoi-ky',
    title: 'Hồi Ký',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJaqPhkAbXrNTQ-PK',
    slug: 'dat-va-nguoi-nam-bo',
    title: 'Đất Và Người Nam Bộ',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJb8umZ58kQAHdx7f',
    slug: 'tu-lieu',
    title: 'Tư Liệu',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJb8wN0zApnXRS2Qg',
    slug: 'truyen-lich-su',
    title: 'Truyện Lịch Sử',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJb8yP74yxATPa09U',
    slug: 'kinh-dien-viet-nam',
    title: 'Kinh Điển Việt Nam',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJbHbG4dc3dtpLvmG',
    slug: 'tam-ly-xa-hoi',
    title: 'Tâm Lý Xã Hội',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJbMIiBdJCYqVExcE',
    slug: 'lich-su-the-gioi',
    title: 'Lịch Sử Thế Giới',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJbOJSCj5zed70Ula',
    slug: 'kien-thuc-tong-hop',
    title: 'Kiến Thức Tổng Hợp',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJbruYZ6CuB-x8WmN',
    slug: 'kiem-hiep',
    title: 'Kiếm Hiệp',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJbrxd9GvYhsQ94c9',
    slug: 'van-hoc-nuoc-ngoai',
    title: 'Văn Học Nước Ngoài',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJbw3VUeoPWlT-6N9',
    slug: 'nuoi-day-con',
    title: 'Nuôi Dạy Con',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJcBJ7P80wSUQdPBr',
    slug: 'chung-khoan',
    title: 'Chứng Khoán',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJcFxz2gXT8IgGqM7',
    slug: 'bai-hoc-kinh-doanh',
    title: 'Bài Học Kinh Doanh',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJcG0c5AbOQbtnBi7',
    slug: 'doanh-nhan',
    title: 'Doanh Nhân',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJcYMcfpjbiR123hx',
    slug: 'quan-ly-tai-chinh',
    title: 'Quản Lý Tài Chính',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJcYOYINm_YL0mIpW',
    slug: 'danh-nhan-the-gioi',
    title: 'Danh Nhân Thế Giới',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJcZqYqXIqKNbAR8K',
    slug: 'hon-nhan-gia-dinh',
    title: 'Hôn Nhân-Gia Đình',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJcyhSkj4AnlMRKlD',
    slug: 'bat-dong-san',
    title: 'Bất Động Sản',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJdBIEcbRBNDd2W43',
    slug: 'triet-hoc',
    title: 'Triết Học',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrJdHkW8WGTfen2Jsj',
    slug: 'thien-chua',
    title: 'Thiên Chúa',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrNAhoOoJ8fBzRJhQU',
    slug: 'tien-hiep',
    title: 'Tiên Hiệp',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrNAk1M7IuLePAW51E',
    slug: 'huyen-huyen',
    title: 'Huyền Huyễn',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrNAkev1RsN2wlHsCP',
    slug: 'lich-su',
    title: 'Lịch Sử',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrNAkrxmXmisl1A0w7',
    slug: 'xuyen-khong',
    title: 'Xuyên Không',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrO3LqN_wAqoDTseOE',
    slug: 'van-hoc-mien-nam',
    title: 'Văn Học Miền Nam',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrOB9oHc3i65Qw9v7s',
    slug: 'kinh-te-hoc',
    title: 'Kinh Tế Học',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NSrOBBX2t_0Ifi_zNuR',
    slug: 'dan-ong',
    title: 'Đàn Ông',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NT0hp5yQukt2DGrFfBD',
    slug: 'chinh-tri',
    title: 'Chính Trị',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NT0hpfO3sRh6MUq5PX2',
    slug: 'nhac-khong-loi',
    title: 'Nhạc Không Lời',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NT0i11yHG4Dnj5xNJxi',
    slug: 'truyen-ngan',
    title: 'Truyện ngắn',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NT0i1jpIfjvyVWZM2Tn',
    slug: 'tu-vi-phong-thuy',
    title: 'Tử Vi-Phong Thủy',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NT0iEYMcYGS_oclQvh3',
    slug: 'tho-hay',
    title: 'Thơ Hay',
    description: '',
    titleEnglish: '',
  },
  {
    key: '-NT0iRWMAy05HEFwj_3U',
    slug: 'ca-dao-tuc-ngu',
    title: 'Ca Dao-Tục Ngữ',
    description: '',
    titleEnglish: '',
  },
];
